export const GET_POKEMON = "GET_POKEMON";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const SAVE_TO_MY_POKEMON = "SAVE_TO_MY_POKEMON";
export const DELETE_FROM_MY_POKEMON = "DELETE_FROM_MY_POKEMON";
export const GET_MY_POKEDEX = "GET_MY_POKEDEX";
